USE [EnglishTeamsDB]
--a)DIRTY READS
--PROBLEM:
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
	SELECT * FROM Teams
	WAITFOR DELAY '00:00:15'
	SELECT * FROM Teams
COMMIT TRAN

--SOLUTION:
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
	SELECT * FROM Teams
	WAITFOR DELAY '00:00:15'
	SELECT * FROM Teams
COMMIT TRAN

--b)NON-REPEATABLE READS
--PROBLEM:
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
	SELECT * FROM Teams
	WAITFOR DELAY '00:00:10'
	SELECT * FROM Teams
COMMIT TRAN

--SOLUTION:
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
	SELECT * FROM Teams
	WAITFOR DELAY '00:00:10'
	SELECT * FROM Teams
COMMIT TRANSACTION

--c)PHANTOM READS:
--PROBLEM:
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
	SELECT * FROM Teams WHERE CityID = 9
	WAITFOR DELAY '00:00:05'
	SELECT * FROM Teams WHERE CityID = 9
COMMIT TRAN

--SOLUTION:
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
	SELECT * FROM Teams WHERE CityID = 9
	WAITFOR DELAY '00:00:05'
	SELECT * FROM Teams WHERE CityID = 9
COMMIT TRAN
